apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: microservice.local
      http:
        paths:
          # Backend API (rewritten)
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8000

          # Backend OpenAPI (NO rewrite)
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          # Backend docs (NO rewrite)
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          # Frontend catchâ€‘all
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80